# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04grpc\"\x19\n\tSporocilo\x12\x0c\n\x04text\x18\x01 \x01(\t2<\n\x07Naloga1\x12\x31\n\rVrniSporocilo\x12\x0f.grpc.Sporocilo\x1a\x0f.grpc.Sporocilob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPOROCILO._serialized_start=20
  _SPOROCILO._serialized_end=45
  _NALOGA1._serialized_start=47
  _NALOGA1._serialized_end=107
# @@protoc_insertion_point(module_scope)
