# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class Naloga1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VrniSporocilo = channel.unary_unary(
                '/grpc.Naloga1/VrniSporocilo',
                request_serializer=test__pb2.Sporocilo.SerializeToString,
                response_deserializer=test__pb2.Sporocilo.FromString,
                )


class Naloga1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def VrniSporocilo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Naloga1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VrniSporocilo': grpc.unary_unary_rpc_method_handler(
                    servicer.VrniSporocilo,
                    request_deserializer=test__pb2.Sporocilo.FromString,
                    response_serializer=test__pb2.Sporocilo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Naloga1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Naloga1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VrniSporocilo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Naloga1/VrniSporocilo',
            test__pb2.Sporocilo.SerializeToString,
            test__pb2.Sporocilo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
