# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ts_pb2 as ts__pb2


class SendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOne = channel.unary_unary(
                '/grpc.Send/SendOne',
                request_serializer=ts__pb2.Point.SerializeToString,
                response_deserializer=ts__pb2.Empty.FromString,
                )
        self.SendMore = channel.stream_unary(
                '/grpc.Send/SendMore',
                request_serializer=ts__pb2.Point.SerializeToString,
                response_deserializer=ts__pb2.Empty.FromString,
                )


class SendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMore(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOne': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOne,
                    request_deserializer=ts__pb2.Point.FromString,
                    response_serializer=ts__pb2.Empty.SerializeToString,
            ),
            'SendMore': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMore,
                    request_deserializer=ts__pb2.Point.FromString,
                    response_serializer=ts__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Send', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Send(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Send/SendOne',
            ts__pb2.Point.SerializeToString,
            ts__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMore(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grpc.Send/SendMore',
            ts__pb2.Point.SerializeToString,
            ts__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ViewStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/grpc.View/GetOne',
                request_serializer=ts__pb2.Point.SerializeToString,
                response_deserializer=ts__pb2.Point.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/grpc.View/GetAll',
                request_serializer=ts__pb2.Empty.SerializeToString,
                response_deserializer=ts__pb2.Point.FromString,
                )


class ViewServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ViewServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=ts__pb2.Point.FromString,
                    response_serializer=ts__pb2.Point.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=ts__pb2.Empty.FromString,
                    response_serializer=ts__pb2.Point.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.View', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class View(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.View/GetOne',
            ts__pb2.Point.SerializeToString,
            ts__pb2.Point.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.View/GetAll',
            ts__pb2.Empty.SerializeToString,
            ts__pb2.Point.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
