# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ts.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"$\n\x05Point\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\r\n\x05value\x18\x02 \x01(\x02\"\x19\n\tPointTime\x12\x0c\n\x04time\x18\x01 \x01(\x02\x32S\n\x04Send\x12#\n\x07SendOne\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty\x12&\n\x08SendMore\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty(\x01\x32P\n\x04View\x12\"\n\x06GetOne\x12\x0b.grpc.Point\x1a\x0b.grpc.Point\x12$\n\x06GetAll\x12\x0b.grpc.Empty\x1a\x0b.grpc.Point0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=18
  _EMPTY._serialized_end=25
  _POINT._serialized_start=27
  _POINT._serialized_end=63
  _POINTTIME._serialized_start=65
  _POINTTIME._serialized_end=90
  _SEND._serialized_start=92
  _SEND._serialized_end=175
  _VIEW._serialized_start=177
  _VIEW._serialized_end=257
# @@protoc_insertion_point(module_scope)
