# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ts_pb2 as ts__pb2


class ServeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOne = channel.unary_unary(
                '/grpc.Serve/SendOne',
                request_serializer=ts__pb2.Point.SerializeToString,
                response_deserializer=ts__pb2.Empty.FromString,
                )
        self.SendMore = channel.stream_unary(
                '/grpc.Serve/SendMore',
                request_serializer=ts__pb2.Point.SerializeToString,
                response_deserializer=ts__pb2.Empty.FromString,
                )
        self.GetOne = channel.unary_unary(
                '/grpc.Serve/GetOne',
                request_serializer=ts__pb2.PointIndex.SerializeToString,
                response_deserializer=ts__pb2.Point.FromString,
                )
        self.GetAll = channel.unary_stream(
                '/grpc.Serve/GetAll',
                request_serializer=ts__pb2.Empty.SerializeToString,
                response_deserializer=ts__pb2.Point.FromString,
                )


class ServeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMore(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOne': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOne,
                    request_deserializer=ts__pb2.Point.FromString,
                    response_serializer=ts__pb2.Empty.SerializeToString,
            ),
            'SendMore': grpc.stream_unary_rpc_method_handler(
                    servicer.SendMore,
                    request_deserializer=ts__pb2.Point.FromString,
                    response_serializer=ts__pb2.Empty.SerializeToString,
            ),
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=ts__pb2.PointIndex.FromString,
                    response_serializer=ts__pb2.Point.SerializeToString,
            ),
            'GetAll': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=ts__pb2.Empty.FromString,
                    response_serializer=ts__pb2.Point.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Serve', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Serve(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Serve/SendOne',
            ts__pb2.Point.SerializeToString,
            ts__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMore(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/grpc.Serve/SendMore',
            ts__pb2.Point.SerializeToString,
            ts__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Serve/GetOne',
            ts__pb2.PointIndex.SerializeToString,
            ts__pb2.Point.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Serve/GetAll',
            ts__pb2.Empty.SerializeToString,
            ts__pb2.Point.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
