# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ts.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x16\n\x05Point\x12\r\n\x05value\x18\x02 \x01(\x02\"\x1b\n\nPointIndex\x12\r\n\x05index\x18\x01 \x01(\x05\x32\xa3\x01\n\x05Serve\x12#\n\x07SendOne\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty\x12&\n\x08SendMore\x12\x0b.grpc.Point\x1a\x0b.grpc.Empty(\x01\x12\'\n\x06GetOne\x12\x10.grpc.PointIndex\x1a\x0b.grpc.Point\x12$\n\x06GetAll\x12\x0b.grpc.Empty\x1a\x0b.grpc.Point0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=18
  _EMPTY._serialized_end=25
  _POINT._serialized_start=27
  _POINT._serialized_end=49
  _POINTINDEX._serialized_start=51
  _POINTINDEX._serialized_end=78
  _SERVE._serialized_start=81
  _SERVE._serialized_end=244
# @@protoc_insertion_point(module_scope)
