# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import example_pb2 as example__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in example_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ExampleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendRandomText = channel.unary_unary(
                '/grpc.Example/SendRandomText',
                request_serializer=example__pb2.Empty.SerializeToString,
                response_deserializer=example__pb2.Text.FromString,
                _registered_method=True)
        self.StreamRandomInt = channel.unary_stream(
                '/grpc.Example/StreamRandomInt',
                request_serializer=example__pb2.Empty.SerializeToString,
                response_deserializer=example__pb2.Int.FromString,
                _registered_method=True)
        self.ObtainRandomFloatStream = channel.stream_unary(
                '/grpc.Example/ObtainRandomFloatStream',
                request_serializer=example__pb2.Floating.SerializeToString,
                response_deserializer=example__pb2.Empty.FromString,
                _registered_method=True)


class ExampleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendRandomText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRandomInt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtainRandomFloatStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendRandomText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRandomText,
                    request_deserializer=example__pb2.Empty.FromString,
                    response_serializer=example__pb2.Text.SerializeToString,
            ),
            'StreamRandomInt': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRandomInt,
                    request_deserializer=example__pb2.Empty.FromString,
                    response_serializer=example__pb2.Int.SerializeToString,
            ),
            'ObtainRandomFloatStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ObtainRandomFloatStream,
                    request_deserializer=example__pb2.Floating.FromString,
                    response_serializer=example__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Example', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc.Example', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Example(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendRandomText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc.Example/SendRandomText',
            example__pb2.Empty.SerializeToString,
            example__pb2.Text.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRandomInt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc.Example/StreamRandomInt',
            example__pb2.Empty.SerializeToString,
            example__pb2.Int.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtainRandomFloatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/grpc.Example/ObtainRandomFloatStream',
            example__pb2.Floating.SerializeToString,
            example__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
