# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\x13\n\x04Text\x12\x0b\n\x03val\x18\x02 \x01(\t\"\x12\n\x03Int\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x17\n\x08\x46loating\x12\x0b\n\x03val\x18\x01 \x01(\x02\x32\x9b\x01\n\x07\x45xample\x12)\n\x0eSendRandomText\x12\x0b.grpc.Empty\x1a\n.grpc.Text\x12+\n\x0fStreamRandomInt\x12\x0b.grpc.Empty\x1a\t.grpc.Int0\x01\x12\x38\n\x17ObtainRandomFloatStream\x12\x0e.grpc.Floating\x1a\x0b.grpc.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_TEXT']._serialized_start=32
  _globals['_TEXT']._serialized_end=51
  _globals['_INT']._serialized_start=53
  _globals['_INT']._serialized_end=71
  _globals['_FLOATING']._serialized_start=73
  _globals['_FLOATING']._serialized_end=96
  _globals['_EXAMPLE']._serialized_start=99
  _globals['_EXAMPLE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
